services:
  server:
    image: blogs-backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    container_name: blogs-backend
  app:
    image: blogs-frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    container_name: blogs-frontend
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server